# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "0amy4r7m9n7w5iyynxw5bp8z8k9pz6kqcpzmq58qpphxpdlxn09j";
    sha256bin64 = "0ywxbnhr54imz0igxq7sp8cqlj9hlz7mwg131rw2j6ab99yghr0j";
    version = "52.0.2743.33";
  };
  dev = {
    sha256 = "01y10blkcmbinx42hb2z5b4jl0acl2k5xjakhsh7fwl5g8k58ppw";
    sha256bin64 = "0vjr9h1b9a2nj1rvccscsx5a3m7zxx1w03435dhdyd8zj523b3ia";
    version = "53.0.2756.0";
  };
  stable = {
    sha256 = "0snwljq5f2qqcncfm6psbfbr1p56n3401bm8baryfnzsp0fgx8rk";
    sha256bin64 = "14zh043xq10gv1d6d7j1grgc9y4clfiklg4vckfhb4x0151wkl3y";
    version = "51.0.2704.84";
  };
}
